Sticky panel
PSU-OOE/components pull request #11
Opened 2022-09-14 16:27 UTC by lal65

2022-09-14 17:15 UTC, kjl16 commented on packages/sticky-panel/src/scss/styles.scss
> +  .sticky-panel__content {
Can simplify with &__content

2022-09-14 17:18 UTC, kjl16 requested changes
One minor thing.

2022-09-15 12:14 UTC, lal65 commented on packages/sticky-panel/src/scss/styles.scss
> +  .sticky-panel__content {
@kjl16 - thanks.  Applied the simplification.

2022-09-15 12:50 UTC, kjl16 approved these changes
Looks good - ship it.

2022-09-15 13:04 UTC, merged