135 update parallel navigation component
PSU-OOE/components pull request #136
Opened 2023-03-20 12:54 UTC by kjl16

2023-03-28 15:38 UTC, lal65 requested changes
We can simplify things here.

2023-03-28 15:38 UTC, lal65 commented on packages/patternlab/source/patterns/molecules/parallel-navigation-item/parallel-navigation-item.twig
> +  link_color: 'beaver-blue',
Kill `link_color`.

2023-03-28 15:38 UTC, lal65 commented on packages/patternlab/source/patterns/molecules/parallel-navigation-item/parallel-navigation-item~active.twig
> +  link_color: 'beaver-blue',
Kill `link_color`.

2023-03-28 15:38 UTC, lal65 commented on packages/patternlab/source/patterns/molecules/parallel-navigation-item/parallel-navigation-item~related-active.twig
> +  link_color: 'beaver-blue',
Kill `link_color`.

2023-03-28 15:38 UTC, lal65 commented on packages/patternlab/source/patterns/molecules/parallel-navigation-item/parallel-navigation-item~related.twig
> +  link_color: 'beaver-blue',
Kill `link_color`.

2023-03-28 15:38 UTC, lal65 commented on packages/patternlab/source/patterns/organisms/parallel-navigation/parallel-navigation~beaver-blue.twig
>  } only %}
Kill example.

2023-03-31 14:10 UTC, kjl16 commented
@lal65 , updated the parallel navigation item to use the shorthand setting of link classes.

2023-03-31 19:34 UTC, lal65 approved these changes

2023-04-03 15:24 UTC, mdw15 approved these changes

2023-04-03 15:56 UTC, merged