Modal component
PSU-OOE/components pull request #143
Opened 2023-03-31 19:34 UTC by bnh10

Functionality:
- Sets accessibility-related attributes on the appropriate modal elements
- Shows modal after clicking triggering element and moves focus to the modal container (used a tabindex="0" so the modal container was included in the tab order when hitting shift + tab)
- Hides modal and returns focus to triggering element after clicking/hitting enter key on close button
- Hides modal when clicking on the overlay and moves focus back to triggering element
- Hides modal when hitting escape key and moves focus back to triggering element

2023-04-05 13:42 UTC, lal65 requested changes
Looks to be an excellent start.  The only missing feature that I found was that we will need some sort of focus trap still.  I think we can use keypress listeners for that though, should be pretty easy.

Let me know if you want to meet to go over the javascript suggestions.  I think this is going to be pretty flexible/powerful.

2023-04-05 13:42 UTC, lal65 commented on packages/modal/modal.twig
> +      <button class="modal__close" alt="Close">
I think we need `aria-label` instead of `alt` here.  IIRC `alt` is only usable with `img` elements.

2023-04-05 13:42 UTC, lal65 commented on packages/modal/src/js/scripts.js
> +// to the outer .modal div
I think we can solve this problem using the component JS architecture.

```
// The modal itself doesn't know / care about its triggering element.

// Activation listener.
modal.addEventListener('component:activate', e => {
  modal.modalTrigger = e.detail.modal_trigger // <-- the trigger must pass itself
  showModal(modal);
  moveFocus(modalContainer);
});

// Deactivation listener.
modal.addEventListener('component:deactivate', e => {
  const modalTrigger = modal.modalTrigger;  // <-- still set from component:activate :)
  hideModal(modal);
  moveFocus(modalTrigger);
});

modalCloseBtn.addEventListener("click", () => {
  modal.dispatchEvent(new CustomEvent('component:deactivate'));
});

  // Hiding modal when clicking outside of it and moving focus back to triggering element
  modalOverlay.addEventListener("click", (e) => {
    if ((e.target == modalOverlay) && (modal.classList.contains("show-modal"))) {
      modal.dispatchEvent(new CustomEvent('component:deactivate'));
    }
  });

  // Hiding modal when hitting the escape key and moving focus back to triggering element
  modal.addEventListener("keyup", (e) => {
    if ((e.key == "Escape") || (e.keycode === 27) && (modal.classList.contains("show-modal"))) {
      modal.dispatchEvent(new CustomEvent('component:deactivate'));
    }
  })
```

...then when we go to integrate this, we can hook it up like so:

```
const modal_trigger = document.querySelector('#whatever-selector-to-open-modal');

modal_trigger.addEventListener('click', () => {
  const modal = document.querySelector('#whatever-selector-for-modal');

  // Pass the trigger to the modal when activating it.
  modal.dispatchEvent(new CustomEvent('component:activate', {
    detail: {
      modal_trigger: modal_trigger,
    }
  }));
});`
```

2023-04-05 16:17 UTC, bnh10 commented on packages/modal/modal.twig
> +      <button class="modal__close" alt="Close">
OK, that was pulled directly from the specs, but I can change it.

2023-04-05 16:37 UTC, bnh10 commented on packages/modal/modal.twig
> +      <button class="modal__close" alt="Close">
Pushed up this change.

2023-04-05 16:43 UTC, bnh10 commented on packages/modal/src/scss/styles.scss
> +      background-color: #0064bf; //primary-blue
Updated!

2023-04-05 16:45 UTC, lal65 commented on packages/modal/modal.twig
> +      <button class="modal__close" alt="Close">
Thanks.  I've found that highly specific/technical "must be followed" requirements are often times interspersed with "conceptual" requirements in a lot of the design specs.

It can be difficult to determine which parts of the spec are expected to be faithfully implemented versus those that require more reading between the lines.

2023-04-06 19:43 UTC, lal65 requested changes
One tiny little thing.

2023-04-06 19:43 UTC, lal65 commented on packages/modal/src/js/scripts.js
> +    const modals = document.querySelectorAll(".modal");
`document.querySelectorAll` should probably be changed to `context.querySelectorAll`, otherwise AJAX calls could potentially cause event listeners to be added more than once for all modals present on a page.

2023-04-06 19:57 UTC, bnh10 commented on packages/modal/src/js/scripts.js
> +    const modals = document.querySelectorAll(".modal");
Updated all references to document to context

2023-04-06 20:07 UTC, lal65 requested changes

2023-04-06 20:07 UTC, lal65 commented on packages/modal/src/js/scripts.js
> +            if (context.activeElement === firstFocusableElement) {
`activeElement` only exists on `document`.  On page-load only `context === document`, but on AJAX requests, `context === the wrapping element of the part of the page that changed`.

Lines 69 & 74 will have to refer to `document`, but the change on line 4 is golden.

2023-04-06 20:34 UTC, bnh10 commented on packages/modal/src/js/scripts.js
> +            if (context.activeElement === firstFocusableElement) {
Done

2023-04-06 21:23 UTC, lal65 approved these changes

2023-04-24 21:01 UTC, lal65 requested changes
One tiny little tweak and everything should be perfect.

2023-04-24 21:01 UTC, lal65 commented on packages/modal/src/scss/styles.scss
> +  }
The `visually-hidden` utility class should be provided already, I think?

We can probably safely ax this.

2023-04-25 13:31 UTC, lal65 approved these changes

2023-04-27 20:33 UTC, merged