159 create ajax spinner component
PSU-OOE/components pull request #160
Opened 2023-05-12 19:45 UTC by kjl16

# Description:
Implement spinner component to be used for ajax requests. Adds two new sprites to the sprite component.

### Workfront Task Link
https://pennstateoutreach.my.workfront.com/task/645bc51e0021b9e85cdb2bf37c1434fe/overview

### Adobe XD Link
https://xd.adobe.com/view/578e7d64-d0d4-4fe2-965c-265991967f04-02dd/

### Review environment Link
https://developers.outreach.psu.edu/159-create-ajax-spinner-component/?p=viewall-molecules-spinner

2023-05-12 20:08 UTC, lal65 requested changes
Plus lots of rem functions needed.

2023-05-12 20:08 UTC, lal65 commented on packages/spinner/src/scss/styles.scss
> +}
Repeating a lot of `display: none` stuff in here.

I recommend moving up a bit in the DOM and doing it once.

```
@media (prefers-reduced-motion: reduce) {
  .spinner__animation {
    display: none;
  }
}
```

2023-05-16 18:26 UTC, mdw15 approved these changes

2023-05-17 12:50 UTC, mdw15 approved these changes

2023-05-17 12:52 UTC, merged