Add header componentry
PSU-OOE/components pull request #201
Opened 2023-12-20 17:51 UTC by lal65

# Description:
This is largely new work; some updates to existing work.

### Review environment Link
  https://developers.outreach.psu.edu/bleeding-edge-headers

2024-01-04 20:41 UTC, lal65 commented on packages/header/src/scss/styles.scss
> +    padding: 0 _rem(2);
Nope.

2024-01-05 19:46 UTC, kjl16 requested changes
I didn't find anything glaring, just a few minor notes.

2024-01-05 20:57 UTC, lal65 commented on packages/horizontal-menu/src/scss/styles.scss
> +      box-shadow: _rem(.1) _rem(.3) _rem(.5) rgba($nittany-navy, .75);
Done (and added @supports b/c layer).

2024-01-05 20:57 UTC, lal65 commented on packages/drop-button/src/js/scripts.js
> +  // Whenever the body changes size under 950px, be sure to revalidate all
Probably 800.  Updated the comments.

2024-01-08 16:12 UTC, lal65 commented on packages/more-menu/src/scss/styles.scss
> +}
No changes needed here - I updated the example in pattern lab in a previous commit :)

2024-01-08 16:13 UTC, lal65 commented on packages/more-menu/more-menu.twig
> +  <ul class="more-menu__list">
Done

2024-01-08 18:35 UTC, merged