Form styles
PSU-OOE/components pull request #229
Opened 2024-04-09 14:58 UTC by lal65

# Description:
Implement the most basic element styles for various form related things.
- [x] Details
- [x] Fieldsets
- [x] Forms
- [x] Checkbox inputs
- [x] Color inputs
- [x] Date inputs
- [x] Text inputs
- [x] Email inputs
- [x] File inputs
- [x] Number inputs
- [x] password inputs
- [x] Radio inputs
- [x] Range inputs
- [x] Search inputs
- [x] Phone inputs
- [x] Time inputs
- [x] URL inputs
- [x] labels
- [x] legends
- [x] Selects
- [x] Textareas

New auto-contrasting on existing things.
- [x] 1. Add auto-contrasting to paragraphs and links.
- [x] 2. Add auto-contrasting to alerts.
- [x] 3. Add auto-contrasting to intro forms
![image](https://github.com/PSU-OOE/components/assets/105240977/4c8c6755-ca85-498a-9a47-519b19501e8e)

Add an "info" flavor alert.
![image](https://github.com/PSU-OOE/components/assets/105240977/dfaaad36-f534-451b-9448-e651dfe34cf0)

Add a boatload of examples.

## Metadata
Delete sections that are not relevant.

### Workfront Task Link
  https://pennstateoutreach.my.workfront.com/task/613118040004631d171a19dd2cc5e114/overview
### Adobe XD Link
  https://xd.adobe.com/view/c3926599-fc79-48ce-9ab2-cb4e483bfc33-96c1/
### Review environment Link
  https://developers.outreach.psu.edu/form-styles

2024-04-17 20:02 UTC, lal65 reviewed
Notes - down to `input-checkbox`.

2024-04-17 20:24 UTC, lal65 commented on packages/details/src/scss/_summary.scss
> +  &.form-required::after {
Moved to integration layer.

2024-04-17 20:24 UTC, lal65 commented on packages/input-checkbox/src/scss/styles.scss
> +        color: var(--white);
Axed!

2024-04-17 20:24 UTC, lal65 commented on packages/details/src/scss/_summary.scss
> +  }
Moved to integration layer.

2024-04-18 16:36 UTC, lal65 commented on packages/select/src/scss/styles.scss
> +}
Moved to integration layer

2024-04-18 16:36 UTC, lal65 commented on packages/select/src/scss/styles.scss
> +  &:not([multiple]) {
Combined.

2024-04-18 16:37 UTC, lal65 commented on packages/input-radio/src/scss/styles.scss
> +        }
Removed.

2024-04-18 16:37 UTC, lal65 commented on packages/input-time/src/scss/styles.scss
> +  transition: background-size var(--transition-duration--default) linear;
Axed.

2024-04-18 16:37 UTC, lal65 commented on packages/input-date/src/scss/styles.scss
> +  transition: background-size var(--transition-duration--default) linear;
Nuked.

2024-05-23 13:03 UTC, kjl16 requested changes
Just a couple small things

2024-05-23 13:03 UTC, kjl16 commented on packages/base/src/scss/_tables.scss
> +    &.show td {}
Can delete this

2024-05-23 13:03 UTC, kjl16 commented on packages/base/src/scss/_tables.scss
> +        font-size: var(font-size--small);
--font-size--small

2024-05-24 12:33 UTC, kjl16 approved these changes

2024-05-24 12:49 UTC, merged