Adding optional chevron to appear on navigation tile with/without ima…
PSU-OOE/components pull request #267
Opened 2024-08-01 13:59 UTC by kjl16

# Description:
Provide ability to add optional chevron to navigation tile variants.

### Review environment Link
https://developers.outreach.psu.edu/258-add-chevron-option-to-navigation-tile-image/?p=viewall-organisms-navigation-tile

https://developers.outreach.psu.edu/258-add-chevron-option-to-navigation-tile-image/?p=viewall-organisms-navigation-tile-image

2024-08-01 14:33 UTC, lal65 requested changes

2024-08-01 14:33 UTC, lal65 commented on packages/navigation-tile/navigation-tile.twig
> +        {{ link.label }}
unindent me

2024-08-02 20:35 UTC, lal65 requested changes
It looks like the examples are backwards for the image variety.  Other than that, just resolve the version conflict in package.json and you're good to go here.

2024-08-06 11:57 UTC, kjl16 commented
Examples are updated.

2024-08-06 13:23 UTC, lal65 approved these changes

2024-08-06 13:34 UTC, lal65 approved these changes

2024-08-06 13:34 UTC, merged