Add a footer component
PSU-OOE/components pull request #273
Opened 2024-08-05 14:10 UTC by lal65

# Description:

Do not reveiw yet.

## Metadata

Delete sections that are not relevant.

### Workfront Task Link

### Adobe XD Link

### Review environment Link

2024-08-06 18:28 UTC, lal65 commented on packages/footer/footer.twig
> +        bottom_background in ['dark'] ? 'footer__bottom-container--dark',
```suggestion
        bottom_background not in ['white'] ? 'footer__bottom-container--dark',
```

2024-08-06 18:29 UTC, lal65 commented on packages/footer/footer.twig
> +      <div class="{{ footer_bottom_classes|join(' ') }}" data-{{ bottom_background == 'dark' ? 'dark' : 'light' }}>
```suggestion
      <div class="{{ footer_bottom_classes|join(' ') }}" data-{{ bottom_background != 'white' ? 'dark' : 'light' }}>
```

2024-08-06 18:51 UTC, lal65 reviewed
I made goof ups :(

2024-08-06 18:51 UTC, lal65 commented on packages/patternlab/source/patterns/regions/footer/footer~alternate.twig
> +  bottom_background: 'dark'
bottom\_background: 'white' -- rename example too.

2024-08-06 18:51 UTC, lal65 commented on packages/list/list.twig
> +{% apply spaceless %}
Needs \_list.md docs.

2024-08-06 18:51 UTC, lal65 commented on packages/physical-address/package.json
> +  }
Needs base; oops.

2024-08-07 13:16 UTC, kjl16 requested changes

2024-08-07 13:16 UTC, kjl16 commented on packages/footer/package.json
> +}
Dependency on sprite and background container :) and base?

2024-08-07 14:32 UTC, lal65 commented on packages/footer/package.json
> +}
Tis done.

2024-08-07 17:01 UTC, kjl16 approved these changes

2024-08-07 17:14 UTC, merged