Re-implement the background-container component to meet design needs.
PSU-OOE/components pull request #68
Opened 2022-11-21 22:08 UTC by lal65

The major changes here are...

- There are no longer separate "sprite" and "position" parameters; they've been rolled up into a single "background_image"
- Multiple sprites can be contained by one "background_image" preset and are rendered via sprite components instead of via CSS :before pseudo-selectors.
- The various magic numbers have been separated into their own distinct files to spread out the complexity.
- Users can now pass an array of classes to apply in addition to whatever background classes are already applied.

Matt R. wrote most of the CSS here -- I already went through a review round with it and made a pile of hardenings and rem-ification.

2022-11-22 15:59 UTC, bnh10 reviewed
Nothing stands out to me in the CSS

2022-11-22 19:53 UTC, kjl16 requested changes

2022-11-22 19:53 UTC, kjl16 commented on packages/background-container/background-container.twig
> +		  </div>
tabbing is a bit off around this section.

2022-11-23 16:26 UTC, kjl16 approved these changes

2022-11-23 16:27 UTC, merged