87 open search component
PSU-OOE/components pull request #88
Opened 2022-12-13 14:35 UTC by kjl16

Not looking for complete review or feedback on this, as i'm not sure if this is route we would want to go with this. Integrating open search as a component **Seems** possible, though.

https://developers.outreach.psu.edu/87-open-search-component/?p=viewall-organisms-open-search

2022-12-16 17:18 UTC, lal65 requested changes
Overall, yes -- I think we can add this to the DS.

2022-12-16 17:18 UTC, lal65 commented on package.json
> +    "@psu-ooe/open-search": "workspace:^"
Not sure what this is.  Should probably be reverted.

2022-12-16 17:18 UTC, lal65 commented on packages/open-search/package.json
> +    "@psu-ooe/base": "^1.0"
Looks like we need `sprite` here as well.

2022-12-16 17:18 UTC, lal65 commented on packages/patternlab/source/_meta/_head.twig
> +
Definitely have to dumb down the example :laughing:.

Maybe a "fruit search" for apples, bananas, and oranges instead?  Imagine that the site that the example represents is "Outreach Farm Store".

2022-12-16 17:18 UTC, lal65 commented on packages/open-search/package.json
> +    "@psu-ooe/base": "^1.0"
We should also probably specify `fuse` itself so it's pulled into the build automatically.

I'm not sure what the best approach to auto-loading third party dependencies is yet.  Maybe we'll have to delegate that to the consumer?

2023-01-23 21:25 UTC, kjl16 commented on packages/open-search/package.json
> +    "@psu-ooe/base": "^1.0"
@lal65 , i've looked into this a bit, and I'm not entirely sure the best way to handle this in the node packages either. I am thinking we can leave it up to the consumer of the component to include Fuse - But glad to kick the tires a bit more if you think its worth it. 

Ideally, it would be packaged up as a dependency in the open search component, but i'm at a loss at the moment.

2023-01-26 21:10 UTC, kjl16 commented on packages/open-search/package.json
> +    "@psu-ooe/base": "^1.0"
Thanks for the help with this - I believe we should be good with including fuse.js now.

2023-03-08 20:36 UTC, closed without merging